M48
; DRILL file {KiCad 8.0.4} date 2024-08-25T20:18:54-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-25T20:18:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X2.1787Y-3.0571
X2.1886Y-2.3567
X2.4209Y-3.0571
X2.4308Y-2.3567
M30
